# localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2
---
- hosts: all
  remote_user: vagrant
  become: true
  become_user: root



  tasks:

  - name: Check
    shell: echo testing

  - name: Install packages
    yum: name={{ item }} state=installed
    #when: ansible_os_family == "RedHat"
    loop:
      - tree
      - nano
      - git
      - docker
      - ansible
